### ISSUE TITLE
ec2 ssh 접속

### ISSUE THREAD

**Issue by TonyJHC** [PetComes/server#3]
어제는 id를 인스턴스 ID를 넣어서 접속을 성공했는데 오늘은 안되더라고
ex) ssh -i "aws-ec2-clother.pem" i-0fedb44c23cdf04e7@ec2-3-37-206-169.ap-northeast-2.compute.amazonaws.com
- > permission denied(public key) 이런 오류나왔던거 같아 ! 

그래서 id를 ubuntu로 해야 접속이 되더라고
ex) ssh -i "aws-ec2-clother.pem" ubuntu@ec2-3-37-206-169.ap-northeast-2.compute.amazonaws.com

내가 뭘 잘못했는지 차이가 뭔지 말해줄 수 있어 ?

빌드해서 ec2에 우리 Spring 서버 올릴라고 했는데 접속이 자꾸 안되서 시간 좀 많이 잡아먹었네 ..  결과적으로 아직 못올림..!!

@HanInJu

**Comment by HanInJu** [comment]
다시 보니까 chmod는 한 것 같네!
그러면 ssh 접속할 때 그 키파일로 접속한 기록이 남아서 그러눈 게 맞을거야! ubuntu로 접속한 키파일이랑 ec2-user로 접근하려는 키 파일이 같으니까 어 이거 다른 계정인데 왜 키가 같아 이렇게 생각하고 에러 내는 것 같거든! 위에서 말한 것처럼 .ssh 파일 만져주면 해결될 듯!!

**Comment by TonyJHC** [comment]
오케이 !
