### ISSUE TITLE
EC2 - 파라미터그룹 수정필요

### ISSUE THREAD

**Issue by TonyJHC** [PetComes/server#32]
utf8 에서 utf8... 머시기로 바꿔야 이모티콘 될듯 아마도.. 
![image](https://user-images.githubusercontent.com/72599051/143300676-1331eed5-417e-41f5-9448-5b7415c89824.png)
![image](https://user-images.githubusercontent.com/72599051/143300786-52a32489-8424-4e9b-9a1b-c8e18b55dd3e.png)

**Comment by HanInJu** [comment]
utf8mb4
